(ns pleromanet.paths)

(defn magus [] [:h2 "Magus"])
(defn fool [] [:h2 "Fool"])
(defn high-priestess [] [:h2 "High Priestess"])
(defn empress [] [:h2 "Empress"])
(defn chariot [] [:h2 "Chariot"])
(defn lovers [] [:h2 "Lovers"])
(defn star [] [:h2 "Star"])
(defn heirophant [] [:h2 "Heirophant"])
(defn hanged-man [] [:h2 "Hanged Man"])
(defn adjustment [] [:h2 "Adjustment"])
(defn lust [] [:h2 "Lust"])
(defn hermit [] [:h2 "Hermit"])
(defn wheel-of-fortune [] [:h2 "Wheel of Fortune"])
(defn devil [] [:h2 "Devil"])
(defn tower [] [:h2 "Tower"])
(defn art [] [:h2 "Art"])
(defn aeon [] [:h2 "Aeon"])
(defn sun [] [:h2 "Sun"])
(defn universe [] [:h2 "Universe"])
(defn moon [] [:h2 "Moon"])
(defn emperor [] [:h2 "Emperor"])

